LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Swiggy\\dim_restaurant.csv'
INTO TABLE restaurants
FIELDS TERMINATED BY','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

create table orders(order_id int,	date_id	int,location_id	int,restaurant_id	int,food_id	int,price	float,rating	float,rating_count int
);
create table location(location_id int,	state	text, city	text, location text
);
create table dates(date_id	int, order_date text
);
create table dish(dish_id int,	category	text, dish_name text
);
create table restaurants(restaurant_id int, restaurant_name text
);


select * from orders;
select * from restaurants;
select * from location;
select * from dates;
select * from dish;

describe dates;
describe  orders;
describe  restaurants;
describe  location;
describe  dish;
drop table location;

alter table dates
add day int,
add month int,
add year int,
add quarter int,
add week int,
add month_name varchar(20),
add day_name varchar(20);

update dates
set 
    year = year(new_date),
    month = month(new_date),
    day = day(new_date),
    quarter = quarter(new_date),
    week = week(new_date),
    month_name = monthname(new_date),
    day_name = dayname(new_date);

alter table dates
add new_date date;

update dates
set new_date = str_to_date(order_date, '%d-%m-%y');

alter table orders
rename column food_id to dish_id;

-- How many total orders are placed?
select count(*) as Total_Orders from orders;

-- What is the total revenue generated?
select round(sum(price),2) as Total_Revenue from orders;

-- What is the average order value?
select round(avg(price),2) as Average_Order_Value from orders;

-- How many unique restaurants are present?
select count(distinct(restaurant_name)) as Unique_Restaurants from restaurants;

-- How many unique cities are covered in the dataset?
select count(distinct(city)) as Unique_Cities from location;

-- What is the total number of dishes available?
select count(distinct(dish_name)) as Number_Of_Dishes from dish;

-- What is the average rating across all orders?
select round(avg(rating),2) as Average_Rating from orders;

-- Which are the top 5 restaurants based on total revenue?
select restaurant_name as Restaurant_Name, round(sum(price),2) as Total_Revenue 
from restaurants as r join orders as o on r.restaurant_id = o.restaurant_id
group by Restaurant_Name
order by Total_Revenue desc
limit 5;

-- Which are the top 5 most ordered dishes?
select dish_name as Dish_Name, count(order_id) as Order_Count 
from dish as d join orders as o on d.dish_id = o.dish_id
group by Dish_Name
order by Order_Count desc
limit 5;

-- Which cities generate the highest number of orders?
select city as City, count(order_id) as Number_Of_Orders from location as l 
join orders as o on l.location_id = o.location_id 
group by City order by Number_Of_Orders desc limit 10;

-- What is the total revenue generated by each city?
select city as City, round(sum(price),2) as Total_Revenue from location as l 
join orders as o on l.location_id = o.location_id 
group by City order by Total_Revenue desc;

-- What is the average rating of each restaurant?
select restaurant_name, round(avg(rating),2) as Average_Rating 
from restaurants as r join orders as o on r.restaurant_id = o.restaurant_id 
group by restaurant_name order by Average_Rating desc;

-- Which restaurant has received the highest number of ratings?
select restaurant_name, sum(rating_count_clean) as Number_Of_Rating 
from restaurants as r join orders as o on r.restaurant_id = o.restaurant_id 
group by restaurant_name order by Number_Of_Rating desc;

select count(rating_count) from orders where rating_count = 0;
select count(rating_count_clean) from orders where rating_count_clean = 0;

alter table orders
add rating_count_clean int;

update orders
set rating_count_clean = 
    case 
        when rating is not null and rating_count = 0 then 1
        else rating_count
    end;
    
select * from orders;

-- What is the most popular food category?
select category_clean as Popular_Category, round(sum(rating),2) as Rating 
from dish as d join orders as o on d.dish_id = o.dish_id 
group by Popular_Category order by Rating desc limit 1 offset 1;

select count(category) from dish where category= 'Recommended';

alter table dish 
add category_clean varchar(50),
add is_recommended tinyint(1);

update dish
set
    is_recommended = case 
        when category = 'recommended' then 1 
        else 0 
    end,
    
    category_clean = case 
        when category = 'recommended' then null 
        else category 
    end;
    
alter table dish
modify category_clean varchar(255);

-- Which category generates the highest revenue?
select category as Category, sum(price) as Total_Revenue 
from dish as d join orders as o on d.dish_id = o.dish_id 
group by Category order by Total_Revenue desc limit 1 offset 1;

-- What is the average order value for each city?
select city as City, round(avg(price),2) as Average_Order_Value 
from location as l join orders as o on l.location_id = o.location_id 
group by City;

-- How many orders are placed each day?


select new_date, count(order_id) as total_orders
from orders o join dates d on o.date_id = d.date_id
group by new_date
order by new_date;

-- What is the monthly revenue trend?
select year,month, round(sum(price),2) as Total_Revenue
from orders as o join dates as d on o.date_id = d.date_id
group by year,month
order by year,month;

-- Which month has the highest number of orders?
select month_name, count(*) as Total_Orders
from orders as o join dates as d on o.date_id = d.date_id
group by month_name
order by Total_Orders desc;

-- On which date was the highest revenue recorded?
select new_date as Date, round(sum(price),2) as Total_Revenue
from orders as o join dates as d on o.date_id = d.date_id
group by Date
order by Total_Revenue desc;

-- What is the average number of daily orders?
select avg(Daily_Orders) as Average_Daily_Orders from(select new_date, count(order_id) as Daily_Orders
from orders as o join dates as d on o.date_id = d.date_id
group by new_date) t;

-- Which restaurant has the highest average rating with a minimum of 50 orders?
select restaurant_name ,round(avg(rating),2) as Average_Rating, count(order_id) as Total_Orders
from orders as o join restaurants as r on o.restaurant_id = r.restaurant_id 
group by restaurant_name
having Total_Orders>=50
order by Average_Rating desc limit 1;

-- Which city has the highest average order value?
select city, round(avg(price),2) as Average_Order_Value 
from location as l join orders as o on l.location_id = o.location_id 
group by city order by Average_Order_Value desc;

-- Which restaurant generates high revenue but has low ratings?
select * from orders;

alter table orders
add rating_level varchar(20);

update orders
set rating_level = 
    case 
        when rating >= 4.5 then 'Excellent'
        when rating >= 4.0 then 'Good'
        when rating >= 3.0 then 'Average'
        when rating < 3 then 'Poor'
        else null
    end;
    
select restaurant_name, round(sum(price),2) as Revenue, rating_level as Ratings from orders as o 
join restaurants as r on o.restaurant_id = r.restaurant_id 
group by restaurant_name,rating_level having Ratings = 'Poor' order by Revenue desc;

-- What is the relationship between rating and price?
select 
    case 
        when price < 200 then 'Low'
        when price between 200 and 500 then 'Medium'
        else 'High'
    end as price_category,
    round(avg(rating),2) as avg_rating,
    count(*) as total_orders
from orders
group by case 
        when price < 200 then 'Low'
        when price between 200 and 500 then 'Medium'
        else 'High'
    end;

-- Which restaurants have consistent performance over time?
select 
    restaurant_name,
    count(*) as total_orders,
    min(month) as start_month,
    max(month) as end_month,
    min(monthly_orders) as min_orders,
    max(monthly_orders) as max_orders
from (
    select 
        restaurant_id,
        month,
        count(*) as monthly_orders
    from orders o
    join dates d 
        on o.date_id = d.date_id
    group by o.restaurant_id, d.month
) t
join restaurants r 
    on t.restaurant_id = r.restaurant_id
group by r.restaurant_name
having max(monthly_orders) - min(monthly_orders) < 50
order by total_orders desc;
    
select min(order_date), max(order_date) from dates;

-- Identify top 3 restaurants in each city based on revenue
select city, restaurant_name, Revenue 
from (select city, restaurant_name, round(sum(o.price),2) as Revenue,
		row_number() over (
            partition by city 
            order by sum(price) desc
        ) as rn from orders o join restaurants r on o.restaurant_id = r.restaurant_id 
join location l on o.location_id = l.location_id
group by city, restaurant_name) t
where rn <= 3
order by city, Revenue desc;

-- Which location (area) has the highest order density?
select *
from (
    select 
        l.location,
        round(count(order_id) / count(distinct (date_id)),2) as order_density
    from location l
    join orders o 
        on l.location_id = o.location_id
    group by location
) t
order by order_density desc
limit 10;

select round(count(order_id) / count(distinct (d.date_id)),2) from orders as o join dates as d on o.date_id = d.date_id;

SET SESSION sort_buffer_size = 26214400;

-- Which city should Swiggy focus on for expansion?
select city, count(order_id) as Total_Orders 
from orders as o join location as l on o.location_id = l.location_id 
group by city order by Total_Orders;

-- Which restaurants should be promoted more?
select restaurant_name, count(*) as Total_Orders, round(avg(rating),2) as Average_Rating
from orders as o join restaurants as r on o.restaurant_id = r.restaurant_id
group by restaurant_name
having Total_Orders > 50 and Average_Rating > 4.0
order by Average_Rating desc;

-- Which food category has the highest demand?
select category, count(*) as Total_Orders 
from orders as o join dish as d on o.dish_id = d.dish_id
where is_recommended = 0
group by category
order by Total_Orders desc;

-- Are expensive dishes rated higher than cheaper ones?

alter table orders
add column price_category varchar(20);

update orders
set
	price_category = case 
        when price < 200 then 'Low'
        when price between 200 and 500 then 'Medium'
        else 'High'
    end;

select
case 
        when price < 200 then 'Low'
        when price between 200 and 500 then 'Medium'
        else 'High'
    end as price_category, round(avg(rating),2) as Ratings , count(*) as Total_Orders
from orders as o join dish as d on o.dish_id = d.dish_id
group by case 
        when price < 200 then 'Low'
        when price between 200 and 500 then 'Medium'
        else 'High'
    end
order by price_category;

-- Which restaurants need improvement based on ratings?
select restaurant_name, round(avg(rating),2) as Ratings 
from orders as o join restaurants as r on o.restaurant_id = r.restaurant_id
group by restaurant_name
order by Ratings;

-- Which cities show growing demand over time?
select city, sum(monthly_orders) as Total_Orders, min(month) as start_month, max(month) as end_month, min(monthly_orders) as min_orders, max(monthly_orders) as max_orders from
(select city , month, count(order_id) as monthly_orders from orders as o join dates as d on o.date_id = d.date_id join location as l on o.location_id = l.location_id 
group by city, month) as t
group by city having max(monthly_orders) > min(monthly_orders)
order by Total_Orders desc;

-- Which restaurants have high ratings but low visibility (orders)?
select restaurant_name, rating_level, count(*) as Total_Orders 
from orders as o join restaurants as r on o.restaurant_id = r.restaurant_id
where rating_level = 'Excellent'
group by restaurant_name
order by Total_Orders;

-- Which dishes should be removed or improved?
select d.dish_name, count(*) as total_orders, sum(case when o.rating_level = 'Poor' then 1 else 0 end) as poor_orders
from orders o join dish d on o.dish_id = d.dish_id
group by d.dish_name
having poor_orders > 5
order by poor_orders desc;

-- What are the peak order periods?
select month_name, count(*) as Total_Orders 
from orders as o join dates as d on o.date_id = d.date_id
group by month_name
order by Total_Orders desc;

-- How would you recommend dishes to users?
select dish_name, count(order_id) as Total_Orders, round(avg(rating),2) as Rating, sum(rating_count_clean) as Total_Ratings_Count
from orders as o join dish as d on o.dish_id = d.dish_id 
group by dish_name having Rating > 4.5 and Total_Orders > 50
order by Rating desc;

-- How would you segment restaurants based on performance?
select restaurant_name, round(sum(price),2) as Revenue, round(avg(rating),2) as Average_Rating,
case 
        when round(sum(price),2) >= 100000 and round(avg(rating),2) >= 4 then 'Top Performer'
        when round(sum(price),2) >= 50000 and round(avg(rating),2) >= 3.5 then 'Growth Potential'
        when round(sum(price),2) < 50000 and round(avg(rating),2) < 3.5 then 'Risky'
        else 'Poor Performer'
    end as segment 
from orders as o join restaurants as r on o.restaurant_id = r.restaurant_id
group by restaurant_name order by Revenue desc;


